(define square (lambda (x) (* x x)))
(square 8)
(define fact (lambda (n) (if (< n 2) 1 (* n (fact (- n 1))))))
(fact 5)
(define fib (lambda (n) (if (< n 2) n (+ (fib (- n 1)) (fib (- n 2))))))  
(fib 8)
(if (< 5 10) 'small 'big)
(let* ((a 5) (b (* a 2))) (+ a b))
(and #t #t)
(or () #t)
(not ())
(eq? 5 5)
(pair? '(1 2))
(cdr '(1 2 3 4))