(+ 1 2)
(+ 5 10)
(* 3 4)
(quote atom)
(quote (list of atoms))
(car (quote (first second third)))
(cdr (quote (first second third)))
(atom (quote symbol))
(atom (quote (not an atom)))
(eq (quote same) (quote same))
(eq (quote different) (quote values))
(if (quote t) (quote true-branch) (quote false-branch))
(if nil (quote false-branch) (quote true-branch))
(cons (quote head) (quote tail))
(cons 1 (cons 2 nil))