(+ (* 2 3) (- 8 3))
(cons (quote hello) (cons (quote world) nil))
(if (eq 5 5) (quote yes) (quote no))
(car (quote (first second third)))
(cdr (quote (1 2 3 4)))
(atom 42)
(atom (quote (not atom)))
(null nil)
(null (quote something))
(eq (+ 2 3) 5)